---
- name: Check that Yay is available
  stat:
    path: /bin/yay
  register: yay_result

- name: Installing VS Code
  shell: yes | LANG=C yay -Syy visual-studio-code-bin
  when: yay_result.stat.exists