---
- name: Installing curl
  community.general.pacman:
    name: curl
    state: present

- name: Download Chaotic AUR keyring package
  shell: curl 'https://cf-builds.garudalinux.org/repos/chaotic-aur/chaotic-keyring.pkg.tar.zst' -o /tmp/chaotic-keyring.tar.zst

- name: Download Chaotic AUR mirrorlist package
  shell: curl 'https://cf-builds.garudalinux.org/repos/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' -o /tmp/chaotic-mirrorlist.tar.zst

- name: Installing Chaotic AUR Keyring packages
  community.general.pacman:
    name:
      - /tmp/chaotic-keyring.tar.zst
      - /tmp/chaotic-mirrorlist.tar.zst
    state: present

- name: Removing local Chaotic packages
  ansible.builtin.file:
    path:
      - /tmp/chaotic-keyring.tar.zst
      - /tmp/chaotic-mirrorlist.tar.zst
    state: absent

- name: Adding Chaotic package repository
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [chaotic-aur]
      Include = /etc/pacman.d/chaotic-mirrorlist
  notify: update pacman cache
  
- name: Updating Pacman cache
  meta: flush_handlers
