---
- name: Installing Git
  community.general.pacman:
    name: git
    state: present

- name: Installing GNU Stow
  community.general.pacman:
    name: stow
    state: present

- name: Check if dotfiles already exist
  stat: path=/home/{{ user_name }}/Dotfiles
  register: dotfiles

- name: Cloning dotfiles
  git:
    repo: https://github.com/jhx0/Dotfiles.git
    dest: /home/{{ user_name }}/Dotfiles
  become: true
  become_user: "{{ user_name }}"
  become_method: su
  when: not dotfiles.stat.exists

- name: Delete default configs
  shell: cd /home/{{ user_name }}; rm -f .bashrc .bash_logout .bash_profile .profile
  become: true
  become_user: "{{ user_name }}"
  become_method: su
  when: not dotfiles.stat.exists

- name: Deploying dotfiles for user {{ user_name }}
  shell: cd /home/{{ user_name }}/Dotfiles && stow . 
  become: true
  become_user: "{{ user_name }}"
  become_method: su
  when: not dotfiles.stat.exists