---
- name: Installing Fail2Ban
  community.general.pacman:
    name: fail2ban
    state: present

- name: Copying config file (Fail2Ban)
  template: 
    src: fail2ban/jail.local.j2 
    dest: /etc/fail2ban/jail.local
    mode: 0640
  notify: restarting fail2ban

- name: Enabling Fail2Ban service
  ansible.builtin.systemd_service:
    name: fail2ban
    enabled: true
    masked: no

- name: Restarting Fail2Ban
  meta: flush_handlers